# Generated by Django 5.2.5 on 2025-08-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('imagem', models.URLField()),
                ('descricao', models.TextField()),
                ('curiosidades', models.TextField(blank=True, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('icone', models.URLField()),
                ('imagens_extras', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
