# Generated by Django 5.2.5 on 2025-09-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='icone',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_imagens/'),
        ),
    ]
