# Generated by Django 5.2.5 on 2025-09-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_evento_horario_alter_evento_icone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='icone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
