# Generated by Django 5.2.5 on 2025-09-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_evento_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
