# Generated by Django 5.2.5 on 2025-11-07 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AGR', 'Agressivo'), ('NEU', 'Neutro'), ('AMG', 'Amigavel'), ('IND', 'Indefinido')], default='IND', max_length=3)),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('chance', models.FloatField(default=50.0)),
                ('sucesso', models.SmallIntegerField(default=10)),
                ('fracasso', models.SmallIntegerField(default=-5)),
                ('som', models.URLField(blank=True, null=True)),
                ('animacao', models.URLField(blank=True, null=True)),
                ('karma', models.SmallIntegerField(default=0)),
                ('icone', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habilidades.habilidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
