# Generated by Django 5.2.5 on 2025-10-09 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_alter_evento_imagem'),
        ('item', '0004_item_bonus_captura_alter_item_nome_alter_item_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaQuestoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('escolha_a', models.CharField(max_length=100)),
                ('escolha_b', models.CharField(max_length=100)),
                ('escolha_c', models.CharField(max_length=100)),
                ('resposta_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversa_questoes', to='item.item')),
            ],
            options={
                'verbose_name': 'Questão de Conversa',
                'verbose_name_plural': 'Questões de Conversa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MochilaPocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocoes_capturadas', to='item.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mochila_pocoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mochila - Poção',
                'verbose_name_plural': 'Mochilas - Poções',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='CapturaProgresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField(default=0)),
                ('capturado', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='MochilaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturado_por', to='events.evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mochila_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at'],
                'unique_together': {('user', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='MochilaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturado_por', to='item.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mochila_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at'],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
