# Generated by Django 5.2.5 on 2025-10-06 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0001_initial'),
        ('item', '0004_item_bonus_captura_alter_item_nome_alter_item_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaQuestoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('escolha_a', models.CharField(max_length=100)),
                ('escolha_b', models.CharField(max_length=100)),
                ('escolha_c', models.CharField(max_length=100)),
                ('resposta_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversa_questoes', to='item.item')),
            ],
            options={
                'verbose_name': 'Questão de Conversa',
                'verbose_name_plural': 'Questões de Conversa',
                'ordering': ['id'],
            },
        ),
    ]
