# Generated by Django 5.2.5 on 2025-11-07 19:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0003_capturaprogresso'),
        ('item', '0004_item_bonus_captura_alter_item_nome_alter_item_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capturaprogresso',
            unique_together={('user', 'item')},
        ),
    ]
