# Generated by Django 5.2.5 on 2025-10-25 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0003_capturaprogresso'),
        ('item', '0004_item_bonus_captura_alter_item_nome_alter_item_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capturaprogresso',
            name='foi_ataque_usado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mochilaitem',
            name='foi_captura_forcada',
            field=models.BooleanField(default=False, help_text="Indica se a captura usou 'atacar'"),
        ),
        migrations.AlterUniqueTogether(
            name='capturaprogresso',
            unique_together={('user', 'item')},
        ),
    ]
