# Generated by Django 5.2.5 on 2025-10-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0004_alter_capturaprogresso_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mochilaitem',
            name='foi_captura_forcada',
            field=models.BooleanField(default=False),
        ),
    ]
