# Generated by Django 5.2.5 on 2025-11-07 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0005_mochilaitem_foi_captura_forcada'),
        ('habilidades', '0001_initial'),
        ('item', '0004_item_bonus_captura_alter_item_nome_alter_item_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('habilidade_usada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habilidades.habilidade')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
