# Generated by Django 5.2.5 on 2025-11-10 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0004_capturaprogresso_foi_ataque_usado_and_more'),
        ('captura', '0006_captura'),
    ]

    operations = [
    ]
