# Generated by Django 5.2.5 on 2025-11-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0007_merge_20251109_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='mochilaitem',
            name='ataque',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='mochilaitem',
            name='bonus_ataque_recebido',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mochilaitem',
            name='bonus_vida_recebido',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mochilaitem',
            name='vida_atual',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mochilaitem',
            name='vida_maxima',
            field=models.IntegerField(default=100),
        ),
    ]
