# Generated by Django 5.2.5 on 2025-11-25 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0007_capturaprogresso_conversa_usada'),
        ('captura', '0008_mochilaitem_ataque_mochilaitem_bonus_ataque_recebido_and_more'),
    ]

    operations = [
    ]
