# Generated by Django 5.2.5 on 2025-08-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, unique=True)),
                ('descricao', models.TextField(null=True)),
                ('tipo', models.CharField(choices=[('NEN', 'Sem Tipo'), ('ANI', 'Animal'), ('PLA', 'Planta')], default='NEN', max_length=3)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('peso', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
            ],
        ),
    ]
