# Generated by Django 5.2.5 on 2025-08-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
