# Generated by Django 5.2.5 on 2025-08-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='curiosidades',
            field=models.TextField(blank=True, null=True),
        ),
    ]
