# Generated by Django 5.2.5 on 2025-09-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_curiosidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bonus_captura',
            field=models.IntegerField(blank=True, help_text='Bônus de captura em porcentagem. Aplicavel apenas a poções.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('NEN', 'Sem Tipo'), ('ANI', 'Animal'), ('PLA', 'Planta'), ('POC', 'Poção')], default='NEN', max_length=3),
        ),
    ]
