# Generated by Django 5.2.5 on 2025-11-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_bonus_captura_alter_item_nome_alter_item_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ataque_base',
            field=models.IntegerField(default=10, help_text='Ataque padrão desta espécie'),
        ),
        migrations.AddField(
            model_name='item',
            name='raridade',
            field=models.CharField(choices=[('COMUM', 'Comum'), ('RARO', 'Raro'), ('EPICO', 'Épico'), ('LENDARIO', 'Lendário')], default='COMUM', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='vida_base',
            field=models.IntegerField(default=100, help_text='Vida padrão desta espécie'),
        ),
    ]
