# Generated by Django 5.2.5 on 2025-08-26 03:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_data_nas_usuario_email_usuario_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro'),
        ),
    ]
